image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 1716
    onOpen: ignore

tasks:
  - command: |
      rclone config file
      echo $RCLONE_CONF | base64 --decode > /home/gitpod/.config/rclone/rclone.conf
      kstart5 plasmashell > /dev/null 2>&1 & disown
      python -m pip install -r requirements.txt
