image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - dart-code.dart-code
    - dart-code.flutter
    - nash.awesome-flutter-snippets
    - ms-azuretools.vscode-docker
    - valentjn.vscode-ltex
    - ms-vscode.cmake-tools
    - editorconfig.editorconfig
    - eamodio.gitlens
    - donjayamanne.githistory
    - oderwat.indent-rainbow
    - ritwickdey.liveserver
    - christian-kohler.path-intellisense
    - humao.rest-client
    - pflannery.vscode-versionlens
    - dotjoshjohnson.xml

tasks:
  - command: |
      flutter pub get
      bash ./.gitpod.init_signing.sh
