stages:
  - build

build_web:
  stage: build
  image: cirrusci/flutter:beta
  before_script:
    - sudo apt-get update -qy
    - sudo apt-get install -y p7zip-full
  script:
    - flutter config --enable-web
    - flutter doctor -v
    - flutter build web --profile
    - 7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on ./build/web_debug.7z ./build/web/*
  artifacts:
    paths:
    - build/web_debug.7z

#build_android:
#  stage: build
#
#build_ios:
#  stage: build
#
#build_linux:
#  stage: build
#
#build_windows:
#  stage: build
#
#build_macos:
#  stage: build
#  
