org: xangelix
app: serverless-rcst
service: serverless-rcst

configValidationMode: error

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local
  - serverless-associate-waf
  - serverless-domain-manager

custom:
  tableName: 'users-table-dev'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    pythonBin: python3
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
  associateWaf:
    name: api-libre-red-waf
    version: V2
  customDomain:
    domainName: api.clone-engine.com
    certificateName: '*.clone-engine.com'
    securityPolicy: tls_1_2
    basePath: ''
    createRoute53Record: true
    endpointType: 'regional'
    autoDomain: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  lambdaHashingVersion: "20201221"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  login:
    handler: wsgi_handler.handler
    events:
      - http: 'POST /login'
  register:
    handler: wsgi_handler.handler
    events:
      - http: 'POST /register'

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: username
            AttributeType: S
        KeySchema:
          -
            AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
